### ISSUE TITLE
There is a small mistake in readme.md file

### ISSUE THREAD

**Issue by aadarshkt** [vectorgrp/sil-kit-adapters-qemu#3]
**Describe the issue**
Relative directory is one step behind and not in current directory.

**To Reproduce**
Follow this readme.md instructions [Link to readme file](https://github.com/vectorgrp/sil-kit-adapters-qemu/blob/main/eth/README.md)

**Expected behavior**
It should start the sil-kit-qemu-adapter, but since path is incorrect it will not start it.

**Screenshots**

**Your Environment (please complete the following information):**
 - OS version and platform: Ubuntu 22.04
 - Compiler and CMake version: 3.22.1
 - SIL Kit Version:4.0.55
 - Please include a description of the SIL Kit participants, including which
   controllers are created and the configuration applied to them: QEMU is the sil-kit participant

**Additional context**

**Comment by SvenMorgenthaler** [comment]
Hi @aadarshkt, thank you for creating the issue. SIL Kit 4.0.54 ist the latest release. I built the adapter against it. I'm not able to reproduce what you have described on my Ubuntu 22.04 system. Is it possible that you have typed the following from being inside the "bin" folder?
![image](https://github.com/user-attachments/assets/2c93406b-76b6-4da7-956e-babb287c7801)

Instead of typing the following being inside in the root-folder of the working copy?
![image](https://github.com/user-attachments/assets/29d2b67e-3f04-4af8-b7df-f3e5d7b2e9f7)

**Comment by aadarshkt** [comment]
That's correct this issue can be closed.

**Comment by SvenMorgenthaler** [comment]
> That's correct this issue can be closed.

Thank you for the confirmation!
